---
version: 5.0.0
commit: 'chore(version): :arrow_heading_up: bump to v%.%.%'
files:
  README.md: v%.%.%
  bower.json: '"version": "%.%.%"'
  package.json: '"version": "%.%.%"'
  src/event-hub.js: v%.%.%
